<?php

$active = ['home' => '',
    'about' =>  '',
    'portfolio' =>  '',
    'blog' =>  '',
    'contact' =>  ''];

$active[$activePage] = "id=\"active\"";

echo "<a href=\"index.php\"" . $active['home'] . ">Home</a>
<a href=\"about.php\"" . $active['about'] . ">About Me</a>
<a href=\"portfolio.php\"" . $active['portfolio'] . ">Portfolio</a>
<a href=\"blog.php\"" . $active['blog'] . ">Blog</a>
<a href=\"contact.php\"" . $active['contact'] . ">Contact Me</a>";